-- core/localization.lua
-- Mega.Localization table and GetText function

Mega.Localization = {
    CurrentLanguage = "en", -- Default, will be overwritten by loaded setting
    Strings = {
        -- Notifications
        ["notify_enabled"] = { ru = "ВКЛЮЧЕНО", en = "ENABLED", es = "HABILITADO", pt = "ATIVADO", ko = "활성화됨", ja = "有効", uk = "УВІМКНЕНО" },
        ["notify_disabled"] = { ru = "ВЫКЛЮЧЕН", en = "DISABLED", es = "DESHABILITADO", pt = "DESATIVADO", ko = "비활성화됨", ja = "無効", uk = "ВИМКНЕНО" },
        ["notify_kit_esp_updated"] = { ru = "Kit ESP обновлен", en = "Kit ESP updated", es = "Kit ESP actualizado", pt = "Kit ESP atualizado", ko = "Kit ESP 업데이트됨", ja = "Kit ESP 更新されました", uk = "Kit ESP оновлено" },
        ["notify_kit_esp_on"] = { ru = "Kit ESP включен", en = "Kit ESP enabled", es = "Kit ESP habilitado", pt = "Kit ESP ativado", ko = "Kit ESP 활성화됨", ja = "Kit ESP 有効", uk = "Kit ESP увімкнено" },
        ["notify_kit_esp_off"] = { ru = "Kit ESP выключен", en = "Kit ESP disabled", es = "Kit ESP deshabilitado", pt = "Kit ESP desativado", ko = "Kit ESP 비활성화됨", ja = "Kit ESP 無効", uk = "Kit ESP вимкнено" },
        ["notify_spectate_start"] = { ru = "Наблюдение за %s включено", en = "Spectating %s enabled", es = "Espectando a %s habilitado", pt = "Espectando %s ativado", ko = "%s 관전 활성화됨", ja = "%s 観戦有効", uk = "Спостереження за %s увімкнено" },
        ["notify_spectate_stop"] = { ru = "Наблюдение отключено", en = "Spectating disabled", es = "Espectando deshabilitado", pt = "Espectando desativado", ko = "관전 비활성화됨", ja = "観戦無効", uk = "Спостереження вимкнено" },
        ["notify_keybind_set"] = { ru = "%s привязана к %s", en = "%s bound to %s", es = "%s asignado a %s", pt = "%s vinculado a %s", ko = "%s가 %s에 바인딩됨", ja = "%s が %s にバインド", uk = "%s прив'язано до %s" },
        ["section_settings_config"] = { ru = "💾 УПРАВЛЕНИЕ КОНФИГАМИ", en = "💾 CONFIG MANAGEMENT", es = "💾 GESTIÓN DE CONFIGURACIONES", pt = "💾 GERENCIAMENTO DE CONFIG", ko = "💾 설정 관리", ja = "💾 設定管理", uk = "💾 КЕРУВАННЯ КОНФІГАМИ" },
        ["textbox_config_name"] = { ru = "Введите имя конфига...", en = "Enter config name...", es = "Introduce nombre de config...", pt = "Digite nome do config...", ko = "설정 이름 입력...", ja = "設定名を入力...", uk = "Введіть ім'я конфігу..." },
        ["button_config_save"] = { ru = "💾 Сохранить конфиг", en = "💾 Save Config", es = "💾 Guardar Configuración", pt = "💾 Salvar Configuração", ko = "💾 설정 저장", ja = "💾 設定保存", uk = "💾 Зберегти конфіг" },
        ["button_config_create"] = { ru = "➕ Создать новый конфиг", en = "➕ Create New Config", es = "➕ Crear Nueva Configuración", pt = "➕ Criar Nova Configuração", ko = "➕ 새 설정 만들기", ja = "➕ 新しい設定を作成", uk = "➕ Створити новий конфіг" },
        ["dropdown_config_list"] = { ru = "Выберите конфиг", en = "Select Config", es = "Seleccionar Configuración", pt = "Selecionar Configuração", ko = "설정 선택", ja = "設定選択", uk = "Виберіть конфіг" },
        ["button_config_load"] = { ru = "📂 Загрузить конфиг", en = "📂 Load Config", es = "📂 Cargar Configuración", pt = "📂 Carregar Configuração", ko = "📂 설정 로드", ja = "📂 設定読み込み", uk = "📂 Завантажити конфіг" },
        ["button_config_delete"] = { ru = "🗑️ Удалить конфиг", en = "🗑️ Delete Config", es = "🗑️ Eliminar Configuración", pt = "🗑️ Deletar Configuração", ko = "🗑️ 설정 삭제", ja = "🗑️ 設定削除", uk = "🗑️ Видалити конфіг" },
        ["button_config_refresh"] = { ru = "🔄 Обновить список", en = "🔄 Refresh List", es = "🔄 Actualizar Lista", pt = "🔄 Atualizar Lista", ko = "🔄 목록 새로고침", ja = "🔄 リスト更新", uk = "🔄 Оновити список" },
        ["notify_config_saved"] = { ru = "Конфиг сохранен", en = "Config saved", es = "Configuración guardada", pt = "Configuração salva", ko = "설정 저장됨", ja = "設定保存", uk = "Конфіг збережено" },
        ["notify_config_loaded"] = { ru = "Конфиг загружен", en = "Config loaded", es = "Configuración cargada", pt = "Configuração carregada", ko = "설정 로드됨", ja = "設定読み込み", uk = "Конфіг завантажено" },
        ["notify_config_not_found"] = { ru = "Конфиг не найден", en = "Config not found", es = "Configuración no encontrada", pt = "Configuração não encontrada", ko = "설정 없음", ja = "設定が見つかりません", uk = "Конфіг не знайдено" },
        ["notify_config_deleted"] = { ru = "🗑️ Конфиг удален", en = "🗑️ Config deleted", es = "🗑️ Configuración eliminada", pt = "🗑️ Configuração deletada", ko = "🗑️ 설정 삭제됨", ja = "🗑️ 設定削除", uk = "🗑️ Конфіг видалено" },
        ["notify_enter_name"] = { ru = "⚠️ Введите имя конфига!", en = "⚠️ Enter config name!", es = "⚠️ ¡Introduce nombre!", pt = "⚠️ Digite o nome!", ko = "⚠️ 이름 입력!", ja = "⚠️ 名前を入力!", uk = "⚠️ Введіть ім'я конфігу!" },
        ["notify_fov_color_changed"] = { ru = "🎨 Цвет FOV изменен", en = "🎨 FOV color changed", es = "🎨 Color de FOV cambiado", pt = "🎨 Cor do FOV alterada", ko = "🎨 FOV 색상 변경됨", ja = "🎨 FOV 色変更", uk = "🎨 Колір FOV змінено" },
        ["notify_team_color_changed"] = { ru = "🎨 Цвет команды изменен", en = "🎨 Team color changed", es = "🎨 Color del equipo cambiado", pt = "🎨 Cor do time alterada", ko = "🎨 팀 색상 변경됨", ja = "🎨 チーム色変更", uk = "🎨 Колір команди змінено" },
        ["notify_enemy_color_changed"] = { ru = "🎨 Цвет врага изменен", en = "🎨 Enemy color changed", es = "🎨 Color del enemigo cambiado", pt = "🎨 Cor do inimigo alterada", ko = "🎨 적 색상 변경됨", ja = "🎨 敵色変更", uk = "🎨 Колір ворога змінено" },
        ["notify_theme_changed"] = { ru = "🎨 Цветовая тема изменена", en = "🎨 Theme color changed", es = "🎨 Tema de color cambiado", pt = "🎨 Tema de cor alterado", ko = "🎨 테마 색상 변경됨", ja = "🎨 テーマ色変更", uk = "🎨 Колірну тему змінено" },
        ["notify_chat_cleared"] = { ru = "🧹 Чат очищен", en = "🧹 Chat cleared", es = "🧹 Chat limpiado", pt = "🧹 Chat limpo", ko = "🧹 채팅 지워짐", ja = "🧹 チャットクリア", uk = "🧹 Чат очищено" },
        ["notify_screenshot"] = { ru = "📸 Скриншот сохранен", en = "📸 Screenshot saved", es = "📸 Captura de pantalla guardada", pt = "📸 Screenshot salvo", ko = "📸 스크린샷 저장됨", ja = "📸 スクリーンショット保存", uk = "📸 Скріншот збережено" },
        ["notify_reload"] = { ru = "🔄 Скрипт перезагружается...", en = "🔄 Script reloading...", es = "🔄 Recargando script...", pt = "🔄 Recarregando script...", ko = "🔄 스크립트 재로드 중...", ja = "🔄 スクリプト再読み込み中...", uk = "🔄 Скрипт перезавантажується..." },
        ["notify_cleanup"] = { ru = "🗑️ Скрипт выгружен", en = "🗑️ Script unloaded", es = "🗑️ Script descargado", pt = "🗑️ Script descarregado", ko = "🗑️ 스크립트 언로드됨", ja = "🗑️ スクリプトアンロード", uk = "🗑️ Скрипт вивантажено" },
        ["notify_autofarm_on"] = { ru = "🚜 Авто-ферма ВКЛЮЧЕНА", en = "🚜 Auto-Farm ENABLED", es = "🚜 Auto-Farm HABILITADO", pt = "🚜 Auto-Farm ATIVADO", ko = "🚜 자동 농장 활성화됨", ja = "🚜 自動ファーム有効", uk = "🚜 Авто-ферма УВІМКНЕНА" },
        ["notify_autofarm_off"] = { ru = "🚜 Авто-ферма ВЫКЛЮЧЕНА", en = "🚜 Auto-Farm DISABLED", es = "🚜 Auto-Farm DESHABILITADO", pt = "🚜 Auto-Farm DESATIVADO", ko = "🚜 자동 농장 비활성화됨", ja = "🚜 自動ファーム無効", uk = "🚜 Авто-ферма ВИМКНЕНА" },
        ["toggle_beekeeper"] = { ru = "Пчеловод (Beekeeper)", en = "Beekeeper", es = "Apicultor", pt = "Apicultor", ko = "양봉가", ja = "養蜂家", uk = "Бджоляр" },
        ["toggle_bee_icons"] = { ru = "Показывать иконки", en = "Show Icons", es = "Mostrar Iconos", pt = "Mostrar Ícones", ko = "아이콘 표시", ja = "アイコン表示", uk = "Показувати іконки" },
        ["toggle_bee_highlight"] = { ru = "Подсветка пчел", en = "Show Highlight", es = "Mostrar Resaltado", pt = "Mostrar Destaque", ko = "하이라이트 표시", ja = "ハイライト表示", uk = "Підсвічування бджіл" },
        ["toggle_hive_levels"] = { ru = "Уровни ульев", en = "Show Hive Levels", es = "Niveles de Colmena", pt = "Níveis da Colmeia", ko = "벌집 레벨 표시", ja = "巣箱レベル表示", uk = "Рівні вуликів" },
        ["toggle_auto_catch"] = { ru = "Авто-ловля пчел", en = "Auto Catch Bees", es = "Captura Auto", pt = "Captura Auto", ko = "자동 포획", ja = "自動キャッチ", uk = "Авто-лов" },
        ["toggle_cletus"] = { ru = "Фермер Клетус (Cletus)", en = "Farmer Cletus", es = "Granjero Cletus", pt = "Fazendeiro Cletus", ko = "농부 클레투스", ja = "農夫クレタス", uk = "Фермер Клетус" },
        ["toggle_cletus_harvest"] = { ru = "Авто-сбор урожая", en = "Auto Harvest", es = "Cosecha Auto", pt = "Colheita Auto", ko = "자동 수확", ja = "自動収穫", uk = "Авто-збір врожаю" },
        ["slider_cletus_range"] = { ru = "Дистанция сбора", en = "Harvest Range", es = "Rango de Cosecha", pt = "Alcance da Colheita", ko = "수확 범위", ja = "収穫範囲", uk = "Дистанція збору" },
        ["toggle_cletus_esp"] = { ru = "Подсветка урожая", en = "Crop ESP", es = "ESP de Cultivos", pt = "ESP de Colheita", ko = "작물 ESP", ja = "作物ESP", uk = "Підсвічування врожаю" },
        ["slider_cletus_esp_transparency"] = { ru = "Прозрачность ESP", en = "ESP Transparency", es = "Transparencia ESP", pt = "Transparência ESP", ko = "ESP 투명도", ja = "ESP透明度", uk = "Прозорість ESP" },
        ["toggle_eldertree"] = { ru = "Элдертри (Eldertree)", en = "Eldertree", es = "Eldertree", pt = "Eldertree", ko = "엘더트리", ja = "エルダーツリー", uk = "Елдертрі" },
        ["slider_eldertree_range"] = { ru = "Дистанция сбора", en = "Collect Range", es = "Rango de Recolección", pt = "Alcance de Coleta", ko = "수집 범위", ja = "収集範囲", uk = "Дистанція збору" },
        ["toggle_eldertree_esp"] = { ru = "Подсветка сфер", en = "Orb ESP", es = "ESP de Orbes", pt = "ESP de Orbes", ko = "오브 ESP", ja = "オーブESP", uk = "Підсвічування сфер" },
        ["toggle_eldertree_autocollect"] = { ru = "Авто-сбор сфер", en = "Auto Collect Orbs", es = "Auto Recolectar Orbes", pt = "Auto Coletar Orbes", ko = "오브 자동 수집", ja = "オーブ自動収集", uk = "Авто-збір сфер" },
        ["toggle_star_collector"] = { ru = "Звездный Коллекционер (Star Collector)", en = "Star Collector", es = "Coleccionista de Estrellas", pt = "Coletor de Estrelas", ko = "스타 컬렉터", ja = "スターコレクター", uk = "Зоряний Колекціонер" },
        ["slider_star_collector_range"] = { ru = "Дистанция сбора", en = "Collect Range", es = "Rango de Recolección", pt = "Alcance de Coleta", ko = "수집 범위", ja = "収集範囲", uk = "Дистанція збору" },
        ["toggle_star_collector_esp"] = { ru = "Подсветка звезд", en = "Star ESP", es = "ESP de Estrellas", pt = "ESP de Estrelas", ko = "별 ESP", ja = "スターESP", uk = "Підсвічування зірок" },
        ["toggle_star_collector_autocollect"] = { ru = "Авто-сбор звезд", en = "Auto Collect Stars", es = "Auto Recolectar Estrellas", pt = "Auto Coletar Estrelas", ko = "별 자동 수집", ja = "星自動収集", uk = "Авто-збір зірок" },
        ["toggle_fisherman"] = { ru = "Рыбак (Fisherman)", en = "Fisherman", es = "Pescador", pt = "Pescador", ko = "어부", ja = "漁師", uk = "Рибалка" },
        ["toggle_metal"] = { ru = "Металлоискатель (Metal)", en = "Metal Detector", es = "Detector de Metales", pt = "Detector de Metais", ko = "금속 탐지기", ja = "金属探知機", uk = "Металошукач" },
        ["toggle_metal_esp"] = { ru = "Подсветка металла", en = "Metal ESP", es = "ESP de Metal", pt = "ESP de Metal", ko = "금속 ESP", ja = "金属ESP", uk = "Підсвічування металу" },
        ["toggle_metal_collect"] = { ru = "Авто-сбор металла", en = "Auto Collect Metal", es = "Recolección Auto", pt = "Coleta Auto", ko = "자동 금속 수집", ja = "自動金属収集", uk = "Авто-збір металу" },
        ["toggle_metal_collect_legit"] = { ru = "Авто-сбор металла (Legit)", en = "Auto Collect Metal (Legit)", es = "Recolección Auto (Legit)", pt = "Coleta Auto (Legit)", ko = "자동 금속 수집 (Legit)", ja = "自動金属収集 (Legit)", uk = "Авто-збір металу (Legit)" },
        ["slider_metal_range"] = { ru = "Дистанция сбора", en = "Collect Range", es = "Rango de Recolección", pt = "Alcance de Coleta", ko = "수집 범위", ja = "収集範囲", uk = "Дистанція збору" },
        ["toggle_taliah"] = { ru = "Талия (Taliah)", en = "Taliah", es = "Taliah", pt = "Taliah", ko = "탈리아", ja = "タリア", uk = "Талія" },
        ["toggle_taliah_esp"] = { ru = "Подсветка куриц", en = "Chicken ESP", es = "ESP de Pollos", pt = "ESP de Galinhas", ko = "닭 ESP", ja = "鶏ESP", uk = "Підсвічування курей" },
        ["toggle_taliah_collect"] = { ru = "Авто-сбор куриц", en = "Auto Chickens", es = "Recolección Auto", pt = "Coleta Auto", ko = "자동 닭 수집", ja = "自動鶏収集", uk = "Авто-збір курей" },
        ["toggle_taliah_collect_legit"] = { ru = "Авто-сбор куриц (Legit)", en = "Auto Chickens (legit)", es = "Recolección Auto (Legit)", pt = "Coleta Auto (Legit)", ko = "자동 닭 수집 (Legit)", ja = "自動鶏収集 (Legit)", uk = "Авто-збір курей (Legit)" },
        ["slider_taliah_radius"] = { ru = "Радиус сбора", en = "Collect Radius", es = "Radio de Recolección", pt = "Raio de Coleta", ko = "수집 반경", ja = "収集半径", uk = "Радіус збору" },
        ["slider_taliah_esp_transparency"] = { ru = "Прозрачность ESP", en = "ESP Transparency", es = "Transparencia ESP", pt = "Transparência ESP", ko = "ESP 투명도", ja = "ESP透明度", uk = "Прозорість ESP" },
        ["toggle_noelle"] = { ru = "Noelle", en = "Noelle", es = "Noelle", pt = "Noelle", ko = "Noelle", ja = "Noelle", uk = "Noelle" },
        ["button_noelle_manager"] = { ru = "🎒 Менеджер Noelle", en = "🎒 Noelle Manager", es = "🎒 Gerente Noelle", pt = "🎒 Gerente Noelle", ko = "🎒 노엘 관리자", ja = "🎒 ノエルマネージャー", uk = "🎒 Менеджер Noelle" },
        ["noelle_title"] = { ru = "Менеджер Слаймов Noelle", en = "Noelle Slime Manager", es = "Gerente de Slimes Noelle", pt = "Gerenciador de Slimes Noelle", ko = "노엘 슬라임 관리자", ja = "ノエルスライムマネージャー", uk = "Менеджер Слаймів Noelle" },
        ["noelle_target"] = { ru = "Цель: %s", en = "Target: %s", es = "Objetivo: %s", pt = "Alvo: %s", ko = "목표: %s", ja = "ターゲット: %s", uk = "Ціль: %s" },
        ["noelle_target_none"] = { ru = "Цель: Нет", en = "Target: None", es = "Objetivo: Ninguno", pt = "Alvo: Nenhum", ko = "목표: 없음", ja = "ターゲット: なし", uk = "Ціль: Немає" },
        ["noelle_refresh"] = { ru = "Обновить", en = "Refresh", es = "Actualizar", pt = "Atualizar", ko = "새로 고침", ja = "更新", uk = "Оновити" },
        ["noelle_select_all"] = { ru = "Выбрать все", en = "Select All", es = "Seleccionar todo", pt = "Selecionar tudo", ko = "모두 선택", ja = "すべて選択", uk = "Вибрати все" },
        ["noelle_give"] = { ru = "ДАТЬ", en = "GIVE", es = "DAR", pt = "DAR", ko = "주기", ja = "与える", uk = "ДАТИ" },
        ["noelle_remove"] = { ru = "ВЕРНУТЬ", en = "TAKE BACK", es = "RECUPERAR", pt = "PEGAR DE VOLTA", ko = "회수", ja = "取り戻す", uk = "ПОВЕРНУТИ" },
        ["noelle_bind"] = { ru = "ПРИВЯЗАТЬ", en = "BIND", es = "ATAR", pt = "VINCULAR", ko = "바인드", ja = "バインド", uk = "ПРИВ'ЯЗАТИ" },
        ["noelle_unbind"] = { ru = "ОТВЯЗАТЬ", en = "UNBIND", es = "DESATAR", pt = "DESVINCULAR", ko = "언바인드", ja = "アンバインド", uk = "ВІДВ'ЯЗАТИ" },
        ["noelle_manage"] = { ru = "Игрок: %s", en = "Player: %s", es = "Jugador: %s", pt = "Jogador: %s", ko = "플레이어: %s", ja = "プレイヤー: %s", uk = "Гравець: %s" },
        ["noelle_back"] = { ru = "⬅ Список игроков", en = "⬅ Player List", es = "⬅ Lista de Jugadores", pt = "⬅ Lista de Jogadores", ko = "⬅ 플레이어 목록", ja = "⬅ プレイヤーリスト", uk = "⬅ Список гравців" },
        ["noelle_bound_other"] = { ru = "(Занят)", en = "(Bound)", es = "(Ocupado)", pt = "(Ocupado)", ko = "(바인딩됨)", ja = "(バインド済み)", uk = "(Зайнятий)" },
        ["toggle_noelle_save_binds"] = { ru = "Сохранять привязку", en = "Save Binds", es = "Guardar Ataduras", pt = "Salvar Vínculos", ko = "바인드 저장", ja = "バインド保存", uk = "Зберегти прив'язку" },
        ["keybind_adetunde"] = { ru = "Клавиша активации", en = "Activation Key", es = "Tecla de Activación", pt = "Tecla de Ativação", ko = "활성화 키", ja = "アクティベーションキー", uk = "Клавіша активації" },
        ["toggle_adetunde"] = { ru = "Адетунде (Adetunde)", en = "Adetunde", es = "Adetunde", pt = "Adetunde", ko = "아데툰데", ja = "アデトゥンデ", uk = "Адетунде" },
        ["slider_adetunde_range"] = { ru = "Радиус удара", en = "Hit Range", es = "Rango de Golpe", pt = "Alcance do Golpe", ko = "타격 범위", ja = "ヒット範囲", uk = "Радіус удару" },
        ["slider_adetunde_duration"] = { ru = "Длительность (x10 сек)", en = "Duration (x10 sec)", es = "Duración (x10 seg)", pt = "Duração (x10 seg)", ko = "지속 시간 (x10 초)", ja = "期間 (x10 秒)", uk = "Тривалість (x10 сек)" },
        ["section_combat_killaura"] = { ru = "⚔️ KILLAURA", en = "⚔️ KILLAURA", es = "⚔️ KILLAURA", pt = "⚔️ KILLAURA", ko = "⚔️ 킬라우라", ja = "⚔️ キルオーラ", uk = "⚔️ KILLAURA" },
        ["toggle_killaura"] = { ru = "Killaura", en = "Killaura", es = "Killaura", pt = "Killaura", ko = "킬라우라", ja = "キルオーラ", uk = "Killaura" },
        ["slider_killaura_range"] = { ru = "Дистанция", en = "Range", es = "Rango", pt = "Alcance", ko = "범위", ja = "範囲", uk = "Дистанція" },
        ["slider_killaura_delay"] = { ru = "Задержка (мс)", en = "Delay (ms)", es = "Retraso (ms)", pt = "Atraso (ms)", ko = "지연 (ms)", ja = "遅延 (ms)", uk = "Затримка (мс)" },
        ["slider_bednuke_min_range"] = { ru = "Мин. дистанция", en = "Min Range", es = "Rango Mínimo", pt = "Alcance Mínimo", ko = "최소 범위", ja = "最小範囲", uk = "Мін. дистанція" },
        ["slider_bednuke_delay"] = { ru = "Задержка (мс)", en = "Delay (ms)", es = "Retraso (ms)", pt = "Atraso (ms)", ko = "지연 (ms)", ja = "遅延 (ms)", uk = "Затримка (мс)" },
        ["section_combat_bednuke"] = { ru = "🛏️ BED NUKE", en = "🛏️ BED NUKE", es = "🛏️ BED NUKE", pt = "🛏️ BED NUKE", ko = "🛏️ BED NUKE", ja = "🛏️ BED NUKE", uk = "🛏️ BED NUKE" },
        ["toggle_bednuke"] = { ru = "Bed Nuke", en = "Bed Nuke", es = "Bed Nuke", pt = "Bed Nuke", ko = "Bed Nuke", ja = "Bed Nuke", uk = "Bed Nuke" },
        ["slider_bednuke_range"] = { ru = "Макс. дистанция", en = "Max Range", es = "Rango Máximo", pt = "Alcance Máximo", ko = "최대 범위", ja = "最大範囲", uk = "Макс. дистанція" },
        ["slider_bednuke_packets"] = { ru = "Пакетов за тик", en = "Packets per tick", es = "Paquetes por tick", pt = "Pacotes por tick", ko = "틱당 패킷", ja = "ティックごとのパケット", uk = "Пакетів за тік" },
        ["toggle_killaura_target_esp"] = { ru = "Показывать цель", en = "Show Target", es = "Mostrar Objetivo", pt = "Mostrar Alvo", ko = "대상 표시", ja = "ターゲットを表示", uk = "Показувати ціль" },
        ["tab_home"] = { ru = "🏠 ГЛАВНАЯ", en = "🏠 HOME", es = "🏠 INICIO", pt = "🏠 INÍCIO", ko = "🏠 홈", ja = "🏠 ホーム", uk = "🏠 ГОЛОВНА" },
        ["tab_updates"] = { ru = "📢 ОБНОВЛЕНИЯ", en = "📢 UPDATES", es = "📢 ACTUALIZACIONES", pt = "📢 ATUALIZAÇÕES", ko = "📢 업데이트", ja = "📢 更新", uk = "📢 ОНОВЛЕННЯ" },
        ["tab_esp"] = { ru = "👁️ ESP", en = "👁️ ESP", es = "👁️ ESP", pt = "👁️ ESP", ko = "👁️ ESP", ja = "👁️ ESP", uk = "👁️ ESP" },
        ["tab_aim"] = { ru = "🎯 AIM", en = "🎯 AIM", es = "🎯 PUNTERÍA", pt = "🎯 MIRA", ko = "🎯 조준", ja = "🎯 狙い", uk = "🎯 AIM" },
        ["tab_player"] = { ru = "⚡ ИГРОК", en = "⚡ PLAYER", es = "⚡ JUGADOR", pt = "⚡ JOGADOR", ko = "⚡ 플레이어", ja = "⚡ プレイヤー", uk = "⚡ ГРАВЕЦЬ" },
        ["tab_combat"] = { ru = "🎮 БОЙ", en = "🎮 COMBAT", es = "🎮 COMBATE", pt = "🎮 COMBATE", ko = "🎮 전투", ja = "🎮 戦闘", uk = "🎮 БІЙ" },
        ["tab_visuals"] = { ru = "🌈 ВИЗУАЛЫ", en = "🌈 VISUALS", es = "🌈 VISUALES", pt = "🌈 VISUAIS", ko = "🌈 비주얼", ja = "🌈 ビジュアル", uk = "🌈 ВІЗУАЛИ" },
        ["tab_farm"] = { ru = "🚜 КИТ", en = "🚜 KIT", es = "🚜 KIT", pt = "🚜 KIT", ko = "🚜 키트", ja = "🚜 キット", uk = "🚜 КІТ" },
        ["tab_users"] = { ru = "👥 ИГРОКИ", en = "👥 PLAYERS", es = "👥 JUGADORES", pt = "👥 JOGADORES", ko = "👥 플레이어들", ja = "👥 プレイヤー", uk = "👥 ГРАВЦІ" },
        ["tab_utils"] = { ru = "🔧 УТИЛИТЫ", en = "🔧 UTILITIES", es = "🔧 UTILIDADES", pt = "🔧 UTILITÁRIOS", ko = "🔧 УТИЛІТИ", ja = "🔧 ユーティリティ", uk = "🔧 УТИЛІТИ" },
        ["tab_settings"] = { ru = "⚙️ НАСТРОЙКИ", en = "⚙️ SETTINGS", es = "⚙️ AJUSTES", pt = "⚙️ CONFIGURAÇÕES", ko = "⚙️ 설정", ja = "⚙️ 設定", uk = "⚙️ НАЛАШТУВАННЯ" },
        ["tab_bot"] = { ru = "🤖 БОТ", en = "🤖 BOT", es = "🤖 BOT", pt = "🤖 BOT", ko = "🤖 봇", ja = "🤖 ボット", uk = "🤖 БОТ" },
        ["section_bot_main"] = { ru = "🤖 ОСНОВНОЙ БОТ", en = "🤖 MAIN BOT", es = "🤖 BOT PRINCIPAL", pt = "🤖 BOT PRINCIPAL", ko = "🤖 메인 봇", ja = "🤖 メインボット", uk = "🤖 ОСНОВНИЙ БОТ" },
        ["toggle_bot"] = { ru = "Включить Бота", en = "Enable Bot", es = "Habilitar Bot", pt = "Ativar Bot", ko = "봇 활성화", ja = "ボット有効化", uk = "Увімкнути Бота" },
        ["section_bot_targets"] = { ru = "🎯 ЦЕЛИ БОТА", en = "🎯 BOT TARGETS", es = "🎯 OBJETIVOS DEL BOT", pt = "🎯 ALVOS DO BOT", ko = "🎯 봇 목표", ja = "🎯 ボットのターゲット", uk = "🎯 ЦІЛІ БОТА" },
        ["toggle_bot_beds"] = { ru = "Ломать Кровати", en = "Target Beds", es = "Destruir Camas", pt = "Destruir Camas", ko = "침대 파괴", ja = "ベッドを狙う", uk = "Ламати Ліжка" },
        ["toggle_bot_players"] = { ru = "Атаковать Игроков", en = "Target Players", es = "Atacar Jugadores", pt = "Atacar Jogadores", ko = "플레이어 공격", ja = "プレイヤーを狙う", uk = "Атакувати Гравців" },
        ["toggle_bot_pathfinding"] = { ru = "Умный Маршрут", en = "Smart Pathfinding", es = "Ruta Inteligente", pt = "Busca de Caminho Inteligente", ko = "스마트 경로 찾기", ja = "スマートパスファインディング", uk = "Розумний Маршрут" },
        ["section_bot_modules"] = { ru = "🔌 АВТО-МОДУЛИ БОТА", en = "🔌 BOT AUTO-MODULES", es = "🔌 MÓDULOS AUTO DEL BOT", pt = "🔌 MÓDULOS AUTO DO BOT", ko = "🔌 봇 자동 모듈", ja = "🔌 ボット自動モジュール", uk = "🔌 АВТО-МОДУЛІ БОТА" },
        ["toggle_bot_killaura"] = { ru = "Авто-Killaura", en = "Auto-Killaura", es = "Auto-Killaura", pt = "Auto-Killaura", ko = "자동 킬라우라", ja = "オートキルオーラ", uk = "Авто-Killaura" },
        ["toggle_bot_scaffold"] = { ru = "Авто-Scaffold", en = "Auto-Scaffold", es = "Auto-Scaffold", pt = "Auto-Scaffold", ko = "자동 스캐폴드", ja = "オート足場", uk = "Авто-Scaffold" },
        ["toggle_bot_bednuke"] = { ru = "Авто-Bed Nuke", en = "Auto-Bed Nuke", es = "Auto-Bed Nuke", pt = "Auto-Bed Nuke", ko = "자동 베드 뉴크", ja = "オートベッドヌーク", uk = "Авто-Bed Nuke" },
        ["toggle_bot_antivoid"] = { ru = "Авто-Anti Void", en = "Auto-Anti Void", es = "Auto-Anti Void", pt = "Auto-Anti Void", ko = "자동 안티 보이드", ja = "オートアンチボイド", uk = "Авто-Anti Void" },
        ["toggle_bot_spider"] = { ru = "Авто-Спайдер", en = "Auto-Spider", es = "Auto-Araña", pt = "Auto-Aranha", ko = "자동 스파이더", ja = "オートスパイダー", uk = "Авто-Спайдер" },
        ["title_bar"] = { ru = "💎 TUMBA MEGA SYSTEM v%s 💎", en = "💎 TUMBA MEGA SYSTEM v%s 💎", es = "💎 SISTEMA MEGA TUMBA v%s 💎", pt = "💎 SISTEMA MEGA TUMBA v%s 💎", ko = "💎 TUMBA 메가 시스템 v%s 💎", ja = "💎 TUMBA メガシステム v%s 💎", uk = "💎 TUMBA MEGA SYSTEM v%s 💎" },
        ["title_bar_with_tab"] = { ru = "💎 %s - TUMBA MEGA SYSTEM 💎", en = "💎 %s - TUMBA MEGA SYSTEM 💎", es = "💎 %s - SISTEMA MEGA TUMBA 💎", pt = "💎 %s - SISTEMA MEGA TUMBA 💎", ko = "💎 %s - TUMBA 메가 시스템 💎", ja = "💎 %s - TUMBA メガシステム 💎", uk = "💎 %s - TUMBA MEGA SYSTEM 💎" },
        ["keybind_listening"] = { ru = "Нажмите клавишу...", en = "Press a key...", es = "Presiona una tecla...", pt = "Pressione uma tecla...", ko = "키를 누르세요...", ja = "キーを押してください...", uk = "Натисніть клавішу..." },
        ["keybind_none"] = { ru = "Нет привязки", en = "None", es = "Ninguno", pt = "Nenhum", ko = "없음", ja = "なし", uk = "Немає прив'язки" },
        ["keybind_current"] = { ru = "%s: %s", en = "%s: %s", es = "%s: %s", pt = "%s: %s", ko = "%s: %s", ja = "%s: %s", uk = "%s: %s" },
        ["slider_label"] = { ru = "%s: %s", en = "%s: %s", es = "%s: %s", pt = "%s: %s", ko = "%s: %s", ja = "%s: %s", uk = "%s: %s" },
        ["dropdown_label"] = { ru = " %s:", en = " %s:", es = " %s:", pt = " %s:", ko = " %s:", ja = " %s:", uk = " %s:" },
        ["section_updates_list"] = { ru = "✨ ЧТО НОВОГО В ЭТОЙ ВЕРСИИ?", en = "✨ WHAT'S NEW IN THIS VERSION?", es = "✨ ¿QUÉ HAY DE NUEVO EN ESTA VERSIÓN?", pt = "✨ O QUE HÁ DE NOVO NESTA VERSÃO?", ko = "✨ 이번 버전의 새로운 기능", ja = "✨ このバージョンの新機能", uk = "✨ ЩО НОВОГО В ЦІЙ ВЕРСІЇ?" },
        ["update_text_v5_1"] = { ru = "• [Игрок] Добавлена функция 'Анти-урон от падения BETA'.\n• [Кит] Добавлен 'Авто-кит BETA' для сбора ресурсов (металл, дерево). В будущем список будет расширен.", en = "• [Player] Added 'No Fall Damage BETA' feature.\n• [Kit] Added 'Auto-Kit BETA' for resource gathering (metal, wood). The list will be expanded in the future.", es = "• [Jugador] Añadida la función 'Sin Daño por Caída BETA'.\n• [Kit] Añadido 'Auto-Kit BETA' para recolección de recursos (metal, madera). La lista se ampliará en el futuro.", pt = "• [Jogador] Adicionada a função 'Sem Dano de Queda BETA'.\n• [Kit] Adicionado 'Auto-Kit BETA' para coleta de recursos (metal, madeira). A lista será expandida no futuro.", ko = "• [플레이어] '낙하 피해 없음 BETA' 기능 추가.\n• [키트] 자원 수집을 위한 '자동 키트 BETA' 추가 (금속, 나무). 목록은 추후 확장될 예정입니다.", ja = "• [プレイヤー]「落下ダメージなし BETA」機能を追加。\n• [キット] リソース収集用の「自動キット BETA」を追加（金属、木材）。リストは将来的に拡張されます。", uk = "• [Гравець] Додано функцію 'Анти-шкода від падіння BETA'.\n• [Кіт] Додано 'Авто-кіт BETA' для збору ресурсів (метал, дерево). У майбутньому список буде розширено." },
        ["section_status"] = { ru = "💎 СИСТЕМНЫЙ СТАТУС", en = "💎 SYSTEM STATUS", es = "💎 ESTADO DEL SISTEMA", pt = "💎 STATUS DO SISTEMA", ko = "💎 시스템 상태", ja = "💎 システムステータス", uk = "💎 СИСТЕМНИЙ СТАТУС" },
        ["toggle_autosave"] = { ru = "💾 Авто-сохранение (15с)", en = "💾 Auto-Save (15s)", es = "💾 Auto-Guardado (15s)", pt = "💾 Auto-Salvar (15s)", ko = "💾 자동 저장 (15초)", ja = "💾 自動保存 (15초)", uk = "💾 Авто-збереження (15с)" },
        ["toggle_perf_mode"] = { ru = "⚡ Режим производительности", en = "⚡ Performance Mode", es = "⚡ Modo de rendimiento", pt = "⚡ Modo de desempenho", ko = "⚡ 성능 모드", ja = "⚡ パフォーマンスモード", uk = "⚡ Режим продуктивності" },
        ["toggle_status_indicator"] = { ru = "📊 Показывать индикатор функций", en = "📊 Show Status Indicator", es = "📊 Mostrar Indicador de Estado", pt = "📊 Mostrar Indicador de Status", ko = "📊 상태 표시기 표시", ja = "📊 ステータスインジケーター表示", uk = "📊 Показувати індикатор функцій" },
        ["section_quick_access"] = { ru = "🚀 БЫСТРЫЙ ДОСТУП", en = "🚀 QUICK ACCESS", es = "🚀 ACCESO RÁPIDO", pt = "🚀 ACESSO RÁPIDO", ko = "🚀 빠른 액세스", ja = "🚀 クイックアクセス", uk = "🚀 ШВИДКИЙ ДОСТУП" },
        ["button_esp_toggle"] = { ru = "👁️ ВКЛ/ВЫКЛ ESP", en = "👁️ TOGGLE ESP", es = "👁️ ACTIVAR/DESACTIVAR ESP", pt = "👁️ LIGAR/DESLIGAR ESP", ko = "👁️ ESP 토글", ja = "👁️ ESP トグル", uk = "👁️ УВІМ/ВИМК ESP" },
        ["button_aim_toggle"] = { ru = "🎯 ВКЛ/ВЫКЛ Aim Assist", en = "🎯 TOGGLE Aim Assist", es = "🎯 ACTIVAR/DESACTIVAR Ayuda de puntería", pt = "🎯 LIGAR/DESLIGAR Assistência de Mira", ko = "🎯 조준 보조 토글", ja = "🎯 エイムアシスト トグル", uk = "🎯 УВІМ/ВИМК Aim Assist" },
        ["button_speed_toggle"] = { ru = "⚡ ВКЛ/ВЫКЛ Speed Hack", en = "⚡ TOGGLE Speed Hack", es = "⚡ ACTIVAR/DESACTIVAR Hack de velocidad", pt = "⚡ LIGAR/DESLIGAR Hack de Velocidade", ko = "⚡ 속도 해킹 토글", ja = "⚡ スピードハック トグル", uk = "⚡ УВІМ/ВИМК Speed Hack" },
        ["section_stats"] = { ru = "📊 СТАТИСТИКА СИСТЕМЫ", en = "📊 SYSTEM STATISTICS", es = "📊 ESTADÍSTICAS DEL SISTEMA", pt = "📊 ESTATÍSTICAS DO SISTEMA", ko = "📊 시스템 통계", ja = "📊 システム統計", uk = "📊 СТАТИСТИКА СИСТЕМИ" },
        ["stats_label"] = { ru = "📈 СТАТИСТИКА:\n🎯 Убийств: %d\n💀 Смертей: %d\n🎮 Время игры: %dм", en = "📈 STATISTICS:\n🎯 Kills: %d\n💀 Deaths: %d\n🎮 Play Time: %dm", es = "📈 ESTADÍSTICAS:\n🎯 Asesinatos: %d\n💀 Muertes: %d\n🎮 Tiempo de juego: %dm", pt = "📈 ESTATÍSTICAS:\n🎯 Mortes: %d\n💀 Mortes: %d\n🎮 Tempo de jogo: %dm", ko = "📈 통계:\n🎯 킬: %d\n💀 데스: %d\n🎮 플레이 시간: %dm", ja = "📈 統計:\n🎯 キル: %d\n💀 デス: %d\n🎮 プレイ時間: %dm", uk = "📈 СТАТИСТИКА:\n🎯 Вбивств: %d\n💀 Смертей: %d\n🎮 Час гри: %dхв" },
        ["section_esp_main"] = { ru = "👁️ ОСНОВНЫЕ НАСТРОЙКИ ESP (Игроки)", en = "👁️ MAIN ESP SETTINGS (Players)", es = "👁️ CONFIGURACIONES PRINCIPALES DE ESP (Jugadores)", pt = "👁️ CONFIGURAÇÕES PRINCIPAIS DE ESP (Jogadores)", ko = "👁️ 주요 ESP 설정 (플레이어)", ja = "👁️ メインESP設定 (プレイヤー)", uk = "👁️ ОСНОВНІ НАЛАШТУВАННЯ ESP (Гравці)" },
        ["toggle_esp"] = { ru = "Включить ESP", en = "Enable ESP", es = "Habilitar ESP", pt = "Ativar ESP", ko = "ESP 활성화", ja = "ESP 有効", uk = "Увімкнути ESP" },
        ["section_esp_visuals"] = { ru = "⚙️ НАСТРОЙКИ ВИЗУАЛОВ", en = "⚙️ VISUALS SETTINGS", es = "⚙️ CONFIGURACIONES VISUALES", pt = "⚙️ CONFIGURAÇÕES VISUAIS", ko = "⚙️ 비주얼 설정", ja = "⚙️ ビジュアル設定", uk = "⚙️ НАЛАШТУВАННЯ ВІЗУАЛІВ" },
        ["toggle_esp_boxes"] = { ru = "Показывать боксы", en = "Show Boxes", es = "Mostrar Cajas", pt = "Mostrar Caixas", ko = "박스 표시", ja = "ボックス表示", uk = "Показувати бокси" },
        ["toggle_esp_names"] = { ru = "Показывать имена", en = "Show Names", es = "Mostrar Nombres", pt = "Mostrar Nomes", ko = "이름 표시", ja = "名前表示", uk = "Показувати імена" },
        ["toggle_esp_health"] = { ru = "Показывать здоровье", en = "Show Health", es = "Mostrar Salud", pt = "Mostrar Saúde", ko = "체력 표시", ja = "ヘルス表示", uk = "Показувати здоров'я" },
        ["toggle_esp_distance"] = { ru = "Показывать дистанцию", en = "Show Distance", es = "Mostrar Distancia", pt = "Mostrar Distância", ko = "거리 표시", ja = "距離表示", uk = "Показувати дистанцію" },
        ["toggle_esp_tracers"] = { ru = "Показывать трейсеры", en = "Show Tracers", es = "Mostrar Rastreadores", pt = "Mostrar Traçadores", ko = "추적자 표시", ja = "トレーサー表示", uk = "Показувати трейсери" },
        ["toggle_esp_team"] = { ru = "Показывать команду", en = "Show Team", es = "Mostrar Equipo", pt = "Mostrar Time", ko = "팀 표시", ja = "チーム表示", uk = "Показувати команду" },
        ["slider_esp_max_dist"] = { ru = "Макс. дистанция ESP", en = "Max ESP Distance", es = "Distancia máxima de ESP", pt = "Distância máxima do ESP", ko = "최대 ESP 거리", ja = "最大ESP距離", uk = "Макс. дистанція ESP" },
        ["section_esp_colors"] = { ru = "🎨 ЦВЕТА ESP", en = "🎨 ESP COLORS", es = "🎨 COLORES DE ESP", pt = "🎨 CORES DO ESP", ko = "🎨 ESP 색상", ja = "🎨 ESP 色", uk = "🎨 КОЛЬОРИ ESP" },
        ["button_team_color"] = { ru = "🎨 Изменить цвет команды", en = "🎨 Change Team Color", es = "🎨 Cambiar Color del Equipo", pt = "🎨 Alterar Cor do Time", ko = "🎨 팀 색상 변경", ja = "🎨 チーム色変更", uk = "🎨 Змінити колір команди" },
        ["button_enemy_color"] = { ru = "🎨 Изменить цвет врага", en = "🎨 Change Enemy Color", es = "🎨 Cambiar Color del Enemigo", pt = "🎨 Alterar Cor do Inimigo", ko = "🎨 적 색상 변경", ja = "🎨 敵色変更", uk = "🎨 Змінити колір ворога" },
        ["section_kit_esp"] = { ru = "🛠️ KIT ESP (Ресурсы и Киты)", en = "🛠️ KIT ESP (Resources & Kits)", es = "🛠️ KIT ESP (Recursos y Kits)", pt = "🛠️ KIT ESP (Recursos e Kits)", ko = "🛠️ KIT ESP (자원 및 키트)", ja = "🛠️ KIT ESP (リソースとキット)", uk = "🛠️ KIT ESP (Ресурси та Кіти)" },
        ["toggle_kit_esp"] = { ru = "Включить Kit ESP", en = "Enable Kit ESP", es = "Habilitar Kit ESP", pt = "Ativar Kit ESP", ko = "Kit ESP 활성화", ja = "Kit ESP 有効", uk = "Увімкнути Kit ESP" },
        ["section_kit_filters"] = { ru = "⚙️ ФИЛЬТРЫ", en = "⚙️ FILTERS", es = "⚙️ FILTROS", pt = "⚙️ FILTROS", ko = "⚙️ 필터", ja = "⚙️ フィルター", uk = "⚙️ ФІЛЬТРИ" },
        ["toggle_kit_iron"] = { ru = "Показывать: Руда (Iron)", en = "Show: Ore (Iron)", es = "Mostrar: Mineral (Hierro)", pt = "Mostrar: Minério (Ferro)", ko = "표시: 광석 (철)", ja = "表示: 鉱石 (鉄)", uk = "Показувати: Руда (Iron)" },
        ["toggle_kit_bee"] = { ru = "Показывать: Пчелиные соты (Bee)", en = "Show: Honeycomb (Bee)", es = "Mostrar: Panal (Abeja)", pt = "Mostrar: Favo (Abelha)", ko = "표시: 벌집 (벌)", ja = "表示: 蜂の巣 (蜂)", uk = "Показувати: Бджолині стільники (Bee)" },
        ["toggle_kit_essence"] = { ru = "Показывать: Эссенция (Nature Essence)", en = "Show: Essence (Nature Essence)", es = "Mostrar: Esencia (Esencia de Naturaleza)", pt = "Mostrar: Essência (Essência Natural)", ko = "표시: 에센스 (자연 에센스)", ja = "表示: 本質 (自然の本質)", uk = "Показувати: Есенція (Nature Essence)" },
        ["toggle_kit_thorns"] = { ru = "Показывать: Шипы (Thorns)", en = "Show: Thorns", es = "Mostrar: Espinas", pt = "Mostrar: Espinhos", ko = "표시: 가시", ja = "表示: 棘", uk = "Показувати: Шипи (Thorns)" },
        ["toggle_kit_mushrooms"] = { ru = "Показывать: Грибы (Mushrooms)", en = "Show: Mushrooms", es = "Mostrar: Hongos", pt = "Mostrar: Cogumelos", ko = "표시: 버섯", ja = "表示: きのこ", uk = "Показувати: Гриби (Mushrooms)" },
        ["toggle_kit_critstar"] = { ru = "Показывать: Звезда Крита (Crit Star)", en = "Show: Crit Star", es = "Mostrar: Estrella Crítica", pt = "Mostrar: Estrela Crítica", ko = "표시: 크리티컬 스타", ja = "表示: クリットスター", uk = "Показувати: Зірка Криту (Crit Star)" },
        ["toggle_kit_vitstar"] = { ru = "Показывать: Звезда Жизни (Vitality Star)", en = "Show: Vitality Star", es = "Mostrar: Estrella de Vitalidad", pt = "Mostrar: Estrela de Vitalidade", ko = "표시: 바이탈리티 스타", ja = "表示: バイタリティスター", uk = "Показувати: Зірка Життя (Vitality Star)" },
        ["toggle_kit_sorcerer"] = { ru = "Показывать: Кристаллы (Sorcerer)", en = "Show: Crystals (Sorcerer)", es = "Mostrar: Cristales (Hechicero)", pt = "Mostrar: Cristais (Feiticeiro)", ko = "표시: 수정 (마법사)", ja = "表示: クリスタル (ソーサラー)", uk = "Показувати: Кристали (Sorcerer)" },
        ["button_kit_esp_apply"] = { ru = "🔄 Применить и Обновить Kit ESP", en = "🔄 Apply and Refresh Kit ESP", es = "🔄 Aplicar y Actualizar Kit ESP", pt = "🔄 Aplicar e Atualizar Kit ESP", ko = "🔄 Kit ESP 적용 및 새로고침", ja = "🔄 Kit ESP 適用と更新", uk = "🔄 Застосувати та Оновити Kit ESP" },
        ["section_aim_main"] = { ru = "🎯 ОСНОВНЫЕ НАСТРОЙКИ AIM", en = "🎯 MAIN AIM SETTINGS", es = "🎯 CONFIGURACIONES PRINCIPALES DE PUNTERÍA", pt = "🎯 CONFIGURAÇÕES PRINCIPAIS DE MIRA", ko = "🎯 주요 조준 설정", ja = "🎯 メインエイム設定", uk = "🎯 ОСНОВНІ НАЛАШТУВАННЯ AIM" },
        ["toggle_aim"] = { ru = "Включить Aim Assist", en = "Enable Aim Assist", es = "Habilitar Ayuda de Puntería", pt = "Ativar Assistência de Mira", ko = "조준 보조 활성화", ja = "エイムアシスト有効", uk = "Увімкнути Aim Assist" },
        ["section_aim_settings"] = { ru = "⚙️ НАСТРОЙКИ ПАРАМЕТРОВ", en = "⚙️ PARAMETER SETTINGS", es = "⚙️ CONFIGURACIONES DE PARÁMETROS", pt = "⚙️ CONFIGURAÇÕES DE PARÂMETROS", ko = "⚙️ 매개변수 설정", ja = "⚙️ パラメータ設定", uk = "⚙️ НАЛАШТУВАННЯ ПАРАМЕТРІВ" },
        ["toggle_aim_show_fov"] = { ru = "Показывать FOV", en = "Show FOV", es = "Mostrar FOV", pt = "Mostrar FOV", ko = "FOV 표시", ja = "FOV 表示", uk = "Показувати FOV" },
        ["button_aim_fov_color"] = { ru = "🎨 Изменить цвет FOV", en = "🎨 Change FOV Color", es = "🎨 Cambiar Color de FOV", pt = "🎨 Alterar Cor do FOV", ko = "🎨 FOV 색상 변경", ja = "🎨 FOV 色変更", uk = "🎨 Змінити колір FOV" },
        ["dropdown_aim_target"] = { ru = "Цель прицела", en = "Aim Target", es = "Objetivo de Puntería", pt = "Alvo da Mira", ko = "조준 목표", ja = "エイムターゲット", uk = "Ціль прицілу" },
        ["dropdown_aim_target_head"] = { ru = "Head (Голова)", en = "Head", es = "Cabeza", pt = "Cabeça", ko = "머리", ja = "頭", uk = "Head (Голова)" },
        ["dropdown_aim_target_upper"] = { ru = "UpperTorso (Верхняя часть тела)", en = "UpperTorso", es = "Torso Superior", pt = "Torso Superior", ko = "상체", ja = "上半身", uk = "UpperTorso (Верхня частина тіла)" },
        ["dropdown_aim_target_lower"] = { ru = "LowerTorso (Нижняя часть тела)", en = "LowerTorso", es = "Torso Inferior", pt = "Torso Inferior", ko = "하체", ja = "下半身", uk = "LowerTorso (Нижня частина тіла)" },
        ["dropdown_aim_target_root"] = { ru = "HumanoidRootPart (Центр)", en = "HumanoidRootPart (Center)", es = "ParteRaízHumanoide (Centro)", pt = "ParteRaizHumanoide (Centro)", ko = "휴머노이드 루트 파트 (중심)", ja = "ヒューマノイドルートパート (中心)", uk = "HumanoidRootPart (Центр)" },
        ["slider_aim_fov"] = { ru = "FOV прицела", en = "Aim FOV", es = "FOV de Puntería", pt = "FOV da Mira", ko = "조준 FOV", ja = "エイムFOV", uk = "FOV прицілу" },
        ["slider_aim_smooth"] = { ru = "Плавность", en = "Smoothness", es = "Suavidad", pt = "Suavidade", ko = "부드러움", ja = "滑らかさ", uk = "Плавність" },
        ["slider_aim_range"] = { ru = "Дальность", en = "Range", es = "Rango", pt = "Alcance", ko = "범위", ja = "範囲", uk = "Дальність" },
        ["section_aim_key"] = { ru = "🎯 КЛАВИША AIM", en = "🎯 AIM KEY", es = "🎯 TECLA DE PUNTERÍA", pt = "🎯 TECLA DE MIRA", ko = "🎯 조준 키", ja = "🎯 エイムキー", uk = "🎯 КЛАВІША AIM" },
        ["keybind_aim"] = { ru = "🔑 Изменить клавишу Aim", en = "🔑 Change Aim Key", es = "🔑 Cambiar Tecla de Puntería", pt = "🔑 Alterar Tecla de Mira", ko = "🔑 조준 키 변경", ja = "🔑 エイムキー変更", uk = "🔑 Змінити клавішу Aim" },
        ["keybind_killaura"] = { ru = "🔑 Клавиша Killaura", en = "🔑 Killaura Key", es = "🔑 Tecla Killaura", pt = "🔑 Tecla Killaura", ko = "🔑 킬라우라 키", ja = "🔑 キルオーラキー", uk = "🔑 Клавіша Killaura" },
        ["keybind_scaffold"] = { ru = "🔑 Клавиша Scaffold", en = "🔑 Scaffold Key", es = "🔑 Tecla Scaffold", pt = "🔑 Tecla Scaffold", ko = "🔑 스캐폴드 키", ja = "🔑 足場キー", uk = "🔑 Клавіша Scaffold" },
        ["toggle_aim_silent"] = { ru = "Тихий прицел", en = "Silent Aim", es = "Puntería Silenciosa", pt = "Mira Silenciosa", ko = "무음 조준", ja = "サイレントエイム", uk = "Тихий приціл" },
        ["toggle_aim_prediction"] = { ru = "Предсказание движения", en = "Movement Prediction", es = "Predicción de Movimiento", pt = "Previsão de Movimento", ko = "움직임 예측", ja = "移動予測", uk = "Передбачення руху" },
        ["toggle_aim_target_hud"] = { ru = "Отображать Target HUD", en = "Show Target HUD", es = "Mostrar Target HUD", pt = "Mostrar Target HUD", ko = "Target HUD 표시", ja = "Target HUD 表示", uk = "Відображати Target HUD" },
        ["toggle_aim_toggle_mode"] = { ru = "Режим переключения (Toggle)", en = "Toggle Mode", es = "Modo de alternancia (Toggle)", pt = "Modo de alternância (Toggle)", ko = "전환 모드 (Toggle)", ja = "切り替えモード (Toggle)", uk = "Режим перемикання (Toggle)" },
        ["section_player_movement"] = { ru = "⚡ ДВИЖЕНИЕ", en = "⚡ MOVEMENT", es = "⚡ MOVIMIENTO", pt = "⚡ MOVIMENTO", ko = "⚡ 이동", ja = "⚡ 移動", uk = "⚡ РУХ" },
        ["toggle_speed"] = { ru = "Спидхак", en = "Speedhack", es = "Hack de Velocidad", pt = "Hack de Velocidade", ko = "속도 해킹", ja = "スピードハック", uk = "Спідхак" },
        ["slider_speed"] = { ru = "Скорость", en = "Speed", es = "Velocidad", pt = "Velocidade", ko = "속도", ja = "速度", uk = "Швидкість" },
        ["toggle_fly"] = { ru = "Режим полета", en = "Fly Mode", es = "Modo Vuelo", pt = "Modo Voo", ko = "비행 모드", ja = "フライモード", uk = "Режим польоту" },
        ["dropdown_fly_mode"] = { ru = "Тип полета", en = "Fly Type", es = "Tipo de Vuelo", pt = "Tipo de Voo", ko = "비행 유형", ja = "飛行タイプ", uk = "Тип польоту" },
        ["slider_fly_speed"] = { ru = "Скорость полета", en = "Fly Speed", es = "Velocidad de Vuelo", pt = "Velocidade de Voo", ko = "비행 속도", ja = "飛行速度", uk = "Швидкість польоту" },
        ["toggle_inf_jump"] = { ru = "Бесконечный прыжок", en = "Infinite Jump", es = "Salto Infinito", pt = "Pulo Infinito", ko = "무한 점프", ja = "無限ジャンプ", uk = "Нескінченний стрибок" },
        ["section_player_defense"] = { ru = "🛡️ ЗАЩИТА", en = "🛡️ DEFENSE", es = "🛡️ DEFENSA", pt = "🛡️ DEFESA", ko = "🛡️ 방어", ja = "🛡️ 防御", uk = "🛡️ ЗАХИСТ" },
        ["toggle_spinbot"] = { ru = "Спин-бот", en = "Spin Bot", es = "Girar Bot", pt = "Bot de Giro", ko = "스핀 봇", ja = "スピンボット", uk = "Спін-бот" },
        ["slider_spinspeed"] = { ru = "Скорость вращения", en = "Spin Speed", es = "Velocidad de Giro", pt = "Velocidade de Giro", ko = "회전 속도", ja = "回転速度", uk = "Швидкість обертання" },
        ["toggle_godmode"] = { ru = "Режим бога", en = "God Mode", es = "Modo Dios", pt = "Modo Deus", ko = "갓 모드", ja = "ゴッドモード", uk = "Режим бога" },
        ["toggle_noclip"] = { ru = "Ноклип", en = "Noclip", es = "Noclip", pt = "Noclip", ko = "노클립", ja = "ノークリップ", uk = "Нокліп" },
        ["toggle_antiknockback"] = { ru = "Анти-отбрасывание", en = "Anti-Knockback", es = "Anti-Retroceso", pt = "Anti-Recuo", ko = "넉백 방지", ja = "ノックバック無効", uk = "Анти-відкидання" },
        ["slider_knockback_strength"] = { ru = "Сила отбрасывания", en = "Knockback Strength", es = "Fuerza de Retroceso", pt = "Força de Recuo", ko = "넉백 강도", ja = "ノックバック強度", uk = "Сила відкидання" },
        ["toggle_nofall"] = { ru = "Анти-урон от падения BETA", en = "No Fall Damage BETA", es = "Sin Daño por Caída BETA", pt = "Sem Dano de Queda BETA", ko = "낙하 피해 없음 BETA", ja = "落下ダメージなし BETA", uk = "Анти-шкода від падіння BETA" },
        ["toggle_antivoid"] = { ru = "Анти-Войд (Левитация)", en = "Anti-Void (Hover)", es = "Anti-Vacío (Vuelo)", pt = "Anti-Vazio (Voo)", ko = "안티 보이드 (부유)", ja = "アンチボイド (ホバー)", uk = "Анти-Войд (Левітація)" },
        ["slider_antivoid_ylevel"] = { ru = "Высота срабатывания (Y)", en = "Trigger Height (Y)", es = "Altura de Activación (Y)", pt = "Altura de Ativação (Y)", ko = "트리거 높이 (Y)", ja = "トリガーの高さ (Y)", uk = "Висота спрацьовування (Y)" },
        ["toggle_antivoid_esp"] = { ru = "Подсветка области", en = "Show Area ESP", es = "Mostrar Área ESP", pt = "Mostrar Área ESP", ko = "영역 ESP 표시", ja = "エリアESPを表示", uk = "Підсвічування області" },
        ["slider_antivoid_esp_transparency"] = { ru = "Прозрачность ESP", en = "ESP Transparency", es = "Transparencia ESP", pt = "Transparência ESP", ko = "ESP 투명도", ja = "ESP透明度", uk = "Прозорість ESP" },
        ["toggle_spider"] = { ru = "Спайдер (Spider)", en = "Spider", es = "Araña", pt = "Aranha", ko = "거미", ja = "スパイダー", uk = "Павук (Spider)" },
        ["dropdown_spider_mode"] = { ru = "Режим Спайдера", en = "Spider Mode", es = "Modo Araña", pt = "Modo Aranha", ko = "거미 모드", ja = "スパイダーモード", uk = "Режим Павука" },
        ["slider_spider_speed"] = { ru = "Скорость Спайдера", en = "Spider Speed", es = "Velocidad de Araña", pt = "Velocidade da Aranha", ko = "거미 속도", ja = "スパイダー速度", uk = "Швидкість Павука" },
        ["toggle_scaffold"] = { ru = "Строитель (Scaffold)", en = "Scaffold", es = "Andamio", pt = "Andaime", ko = "스캐폴드", ja = "足場", uk = "Будівельник (Scaffold)" },
        ["slider_scaffold_yoffset"] = { ru = "Смещение Y (x10)", en = "Y Offset (x10)", es = "Desplazamiento Y (x10)", pt = "Deslocamento Y (x10)", ko = "Y 오프셋 (x10)", ja = "Yオフセット (x10)", uk = "Зсув Y (x10)" },
        ["slider_scaffold_predict"] = { ru = "Предсказание (x100)", en = "Predict (x100)", es = "Predicción (x100)", pt = "Previsão (x100)", ko = "예측 (x100)", ja = "予測 (x100)", uk = "Передбачення (x100)" },
        ["section_antiknockback_settings"] = { ru = "⚙️ НАСТРОЙКИ АНТИ-КНОКБЕКА", en = "⚙️ ANTI-KNOCKBACK SETTINGS", es = "⚙️ CONFIGURACIONES ANTI-RETROCESO", pt = "⚙️ CONFIGURAÇÕES ANTI-RECUO", ko = "⚙️ 넉백 방지 설정", ja = "⚙️ ノックバック無効設定", uk = "⚙️ НАЛАШТУВАННЯ АНТИ-ВІДКИДАННЯ" },
        ["toggle_fastbreak"] = { ru = "Быстрое разрушение", en = "Fast Break", es = "Rotura Rápida", pt = "Quebra Rápida", ko = "빠른 파괴", ja = "高速破壊", uk = "Швидке руйнування" },
        ["section_farm_main"] = { ru = "🚜 ОСНОВНЫЕ НАСТРОЙКИ ФЕРМЫ", en = "🚜 MAIN FARM SETTINGS", es = "🚜 CONFIGURACIONES PRINCIPALES DE GRANJA", pt = "🚜 CONFIGURAÇÕES PRINCIPAIS DA FAZENDA", ko = "🚜 주요 농장 설정", ja = "🚜 主なファーム設定", uk = "🚜 ОСНОВНІ НАЛАШТУВАННЯ ФЕРМИ" },
        ["autofarm_info"] = { ru = "Поддерживаемые ресурсы: Руда, Дерево", en = "Supported resources: Ore, Wood", es = "Recursos soportados: Mineral, Madera", pt = "Recursos suportados: Minério, Madeira", ko = "지원 자원: 광석, 나무", ja = "対応リソース: 鉱石、木", uk = "Підтримувані ресурси: Руда, Дерево" },
        ["notify_autokit_on"] = { ru = "🤖 Авто-кит ВКЛЮЧЕН для '%s'", en = "🤖 Auto-Kit ENABLED for '%s'", es = "🤖 Auto-Kit HABILITADO para '%s'", pt = "🤖 Auto-Kit ATIVADO para '%s'", ko = "🤖 자동 키트 활성화됨: '%s'", ja = "🤖 自動キット有効: '%s'", uk = "🤖 Авто-кіт УВІМКНЕНО для '%s'" },
        ["notify_autokit_off"] = { ru = "🤖 Авто-кит ВЫКЛЮЧЕН", en = "🤖 Auto-Kit DISABLED", es = "🤖 Auto-Kit DESHABILITADO", pt = "🤖 Auto-Kit DESATIVADO", ko = "🤖 자동 키트 비활성화됨", ja = "🤖 自動キット無効", uk = "🤖 Авто-кіт ВИМКНЕНО" },
        ["slider_break_speed"] = { ru = "Скорость разрушения", en = "Break Speed", es = "Velocidad de Rotura", pt = "Velocidade de Quebra", ko = "파괴 속도", ja = "破壊速度", uk = "Швидкість руйнування" },
        ["section_combat_auto"] = { ru = "🎯 АВТОМАТИЗАЦИЯ", en = "🎯 AUTOMATION", es = "🎯 AUTOMATIZACIÓN", pt = "🎯 AUTOMAÇÃO", ko = "🎯 자동화", ja = "🎯 自動化", uk = "🎯 АВТОМАТИЗАЦІЯ" },
        ["toggle_triggerbot"] = { ru = "Триггер-бот", en = "Trigger Bot", es = "Bot de Disparador", pt = "Bot de Gatilho", ko = "트리거 봇", ja = "トリガーボット", uk = "Тригер-бот" },
        ["toggle_autoshoot"] = { ru = "Авто-стрельба", en = "Auto Shoot", es = "Disparo Automático", pt = "Tiro Automático", ko = "자동 사격", ja = "オートシュート", uk = "Авто-стрільба" },
        ["toggle_rapidfire"] = { ru = "Быстрая стрельба", en = "Rapid Fire", es = "Fuego Rápido", pt = "Fogo Rápido", ko = "급속 사격", ja = "ラピッドファイア", uk = "Швидка стрільба" },
        ["section_combat_accuracy"] = { ru = "🎯 ТОЧНОСТЬ", en = "🎯 ACCURACY", es = "🎯 PRECISIÓN", pt = "🎯 PRECISÃO", ko = "🎯 정확도", ja = "🎯 精度", uk = "🎯 ТОЧНІСТЬ" },
        ["toggle_norecoil"] = { ru = "Нет отдачи", en = "No Recoil", es = "Sin Retroceso", pt = "Sem Recuo", ko = "반동 없음", ja = "反動なし", uk = "Без віддачі" },
        ["toggle_nospread"] = { ru = "Нет разброса", en = "No Spread", es = "Sin Dispersión", pt = "Sem Espalhamento", ko = "흩어짐 없음", ja = "拡散なし", uk = "Без розкиду" },
        ["section_visuals_env"] = { ru = "🌍 ОКРУЖЕНИЕ", en = "🌍 ENVIRONMENT", es = "🌍 ENTORNO", pt = "🌍 AMBIENTE", ko = "🌍 환경", ja = "🌍 環境", uk = "🌍 ОТОЧЕННЯ" },
        ["button_visuals_settings"] = { ru = "⚙️ Настроить Визуалы Среды (NoFog, Brightness, Shadows)", en = "⚙️ Adjust Environment Visuals (NoFog, Brightness, Shadows)", es = "⚙️ Ajustar Visuales del Entorno (SinNiebla, Brillo, Sombras)", pt = "⚙️ Ajustar Visuais do Ambiente (Sem Névoa, Brilho, Sombras)", ko = "⚙️ 환경 비주얼 조정 (안개 없음, 밝기, 그림자)", ja = "⚙️ 環境ビジュアル調整 (霧なし、明るさ、影)", uk = "⚙️ Налаштувати Візуали Середовища (NoFog, Brightness, Shadows)" },
        ["toggle_nofog"] = { ru = "Убрать туман", en = "Remove Fog", es = "Eliminar Niebla", pt = "Remover Névoa", ko = "안개 제거", ja = "霧除去", uk = "Прибрати туман" },
        ["toggle_fullbright"] = { ru = "Яркое освещение", en = "Full Bright", es = "Brillo Completo", pt = "Brilho Total", ko = "전체 밝기", ja = "フルブライト", uk = "Яскраве освітлення" },
        ["toggle_nightmode"] = { ru = "Ночной режим", en = "Night Mode", es = "Modo Noche", pt = "Modo Noite", ko = "야간 모드", ja = "ナイトモード", uk = "Нічний режим" },
        ["toggle_removeshadows"] = { ru = "Убрать тени", en = "Remove Shadows", es = "Eliminar Sombras", pt = "Remover Sombras", ko = "그림자 제거", ja = "影除去", uk = "Прибрати тіні" },
        ["section_utils_tools"] = { ru = "🔧 ИНСТРУМЕНТЫ", en = "🔧 TOOLS", es = "🔧 HERRAMIENTAS", pt = "🔧 FERRAMENTAS", ko = "🔧 도구", ja = "🔧 ツール", uk = "🔧 ІНСТРУМЕНТИ" },
        ["button_clear_chat"] = { ru = "🧹 Очистить игровой чат", en = "🧹 Clear Game Chat", es = "🧹 Limpiar Chat del Juego", pt = "🧹 Limpar Chat do Jogo", ko = "🧹 게임 채팅 지우기", ja = "🧹 ゲームチャットクリア", uk = "🧹 Очистити ігровий чат" },
        ["button_screenshot"] = { ru = "📸 Сделать скриншот", en = "📸 Take Screenshot", es = "📸 Tomar Captura de Pantalla", pt = "📸 Tirar Screenshot", ko = "📸 스크린샷 찍기", ja = "📸 スクリーンショット", uk = "📸 Зробити скріншот" },
        ["button_server_info"] = { ru = "🔍 Информация об сервере", en = "🔍 Server Info", es = "🔍 Información del Servidor", pt = "🔍 Info do Servidor", ko = "🔍 서버 정보", ja = "🔍 サーバー情報", uk = "🔍 Інформація про сервер" },
        ["section_utils_fun"] = { ru = "🎪 РАЗВЛЕЧЕНИЯ", en = "🎪 MISC", es = "🎪 VARIOS", pt = "🎪 DIVERSOS", ko = "🎪 기타", ja = "雑多", uk = "🎪 РОЗВАГИ" },
        ["toggle_fame_spam"] = { ru = "Спам в чат", en = "Chat Spam", es = "Spam de Chat", pt = "Spam no Chat", ko = "채팅 스팸", ja = "チャットスパム", uk = "Спам у чат" },
        ["toggle_fames_mom"] = { ru = "Мама Фейма", en = "Fame's Mom", es = "Mamá de Fame", pt = "Mãe do Fame", ko = "페임의 엄마", ja = "フェイムの母", uk = "Мама Фейма" },
        ["toggle_autofish"] = { ru = "🎣 Авто-рыбалка (Legit)", en = "🎣 Auto-Fish (Legit)", es = "🎣 Auto-Pesca (Legit)", pt = "🎣 Auto-Pesca (Legit)", ko = "🎣 자동 낚시 (Legit)", ja = "🎣 自動釣り (Legit)", uk = "🎣 Авто-риболовля (Legit)" },
        ["toggle_autofarm"] = { ru = "Авто-кит BETA", en = "Auto-Kit BETA", es = "Auto-Kit BETA", pt = "Auto-Kit BETA", ko = "자동 키트 BETA", ja = "自動キット BETA", uk = "Авто-кіт BETA" },
        ["toggle_chest_steal"] = { ru = "Авто-лут сундуков", en = "Chest Steal", es = "Robar Cofres", pt = "Roubar Baús", ko = "상자 훔치기", ja = "チェストスチール", uk = "Авто-лут скринь" },
        ["slider_chest_steal_range"] = { ru = "Дистанция лута", en = "Steal Range", es = "Rango de Robo", pt = "Alcance do Roubo", ko = "훔치기 범위", ja = "スチール範囲", uk = "Дистанція луту" },
        ["toggle_chest_esp"] = { ru = "Подсветка сундуков (Chest ESP)", en = "Chest ESP", es = "ESP de Cofres", pt = "ESP de Baús", ko = "상자 ESP", ja = "チェスト ESP", uk = "Підсвічування скринь (Chest ESP)" },
        ["slider_chest_esp_range"] = { ru = "Макс. дистанция", en = "Max Distance", es = "Distancia Máxima", pt = "Distância Máxima", ko = "최대 거리", ja = "最大距離", uk = "Макс. дистанція" },
        ["toggle_auto_deposit"] = { ru = "Авто-склад в личный сундук", en = "Auto Deposit (Personal Chest)", es = "Depósito Automático (Cofre Personal)", pt = "Depósito Automático (Baú Pessoal)", ko = "자동 보관 (개인 상자)", ja = "自動保管 (個人チェスト)", uk = "Авто-склад в особисту скриню" },
        ["slider_auto_deposit_range"] = { ru = "Дистанция склада", en = "Deposit Range", es = "Rango de Depósito", pt = "Alcance do Depósito", ko = "보관 범위", ja = "保管範囲", uk = "Дистанція складу" },
        ["section_deposit_resources"] = { ru = "Ресурсы для склада", en = "Resources to Deposit", es = "Recursos a Depositar", pt = "Recursos para Depositar", ko = "보관할 자원", ja = "保管するリソース", uk = "Ресурси для складу" },
        ["toggle_deposit_iron"] = { ru = "Железо (Iron)", en = "Iron", es = "Hierro", pt = "Ferro", ko = "철", ja = "鉄", uk = "Залізо (Iron)" },
        ["toggle_deposit_diamond"] = { ru = "Алмазы (Diamond)", en = "Diamond", es = "Diamante", pt = "Diamante", ko = "다이아몬드", ja = "ダイヤモンド", uk = "Діаманти (Diamond)" },
        ["toggle_deposit_emerald"] = { ru = "Изумруды (Emerald)", en = "Emerald", es = "Esmeralda", pt = "Esmeralda", ko = "에메랄드", ja = "エメラルド", uk = "Смарагди (Emerald)" },
        ["toggle_deposit_gold"] = { ru = "Золото (Gold)", en = "Gold", es = "Oro", pt = "Ouro", ko = "금", ja = "金", uk = "Золото (Gold)" },
        ["toggle_deposit_void_crystal"] = { ru = "Кристаллы пустоты", en = "Void Crystal", es = "Cristal del Vacío", pt = "Cristal do Vazio", ko = "공허 수정", ja = "ヴォイドクリスタル", uk = "Кристали порожнечі" },
        ["toggle_deposit_wood"] = { ru = "Дерево (Wood)", en = "Wood", es = "Madera", pt = "Madeira", ko = "나무", ja = "木", uk = "Дерево (Wood)" },
        ["toggle_deposit_stone"] = { ru = "Камень (Stone)", en = "Stone", es = "Piedra", pt = "Pedra", ko = "돌", ja = "石", uk = "Камінь (Stone)" },
        ["toggle_lani"] = { ru = "Лани (Lani)", en = "Lani", es = "Lani", pt = "Lani", ko = "라니", ja = "ラニ", uk = "Лані" },
        ["keybind_lani"] = { ru = "Клавиша телепорта", en = "Teleport Key", es = "Tecla de Teletransporte", pt = "Tecla de Teletransporte", ko = "텔레포트 키", ja = "テレポートキー", uk = "Клавіша телепорту" },
        ["lani_target"] = { ru = "Цель: %s", en = "Target: %s", es = "Objetivo: %s", pt = "Alvo: %s", ko = "목표: %s", ja = "ターゲット: %s", uk = "Ціль: %s" },
        ["button_reload_script"] = { ru = "🔄 Релоад скрипта", en = "🔄 Reload Script", es = "🔄 Recargar Script", pt = "🔄 Recarregar Script", ko = "🔄 스크립트 재로드", ja = "🔄 スクリプト再読み込み", uk = "🔄 Релоад скрипта" },
        ["section_settings_appearance"] = { ru = "🎨 ВНЕШНИЙ ВИД", en = "🎨 APPEARANCE", es = "🎨 APARIENCIA", pt = "🎨 APARECÊNCIA", ko = "🎨 외관", ja = "🎨 外観", uk = "🎨 ЗОВНІШНІЙ ВИГЛЯД" },
        ["button_change_theme"] = { ru = "🌈 Сменить цветовую тему", en = "🌈 Change Color Theme", es = "🌈 Cambiar Tema de Color", pt = "🌈 Alterar Tema de Cor", ko = "🌈 색상 테마 변경", ja = "🌈 カラーテーマ変更", uk = "🌈 Змінити колірну тему" },
        ["dropdown_language"] = { ru = "Язык интерфейса", en = "Interface Language", es = "Idioma de Interfaz", pt = "Idioma da Interface", ko = "인터페이스 언어", ja = "インターフェース言語", uk = "Мова інтерфейсу" },
        ["language_english"] = { ru = "English (Английский)", en = "English", es = "English (Inglés)", pt = "English (Inglês)", ko = "English (영어)", ja = "English (英語)", uk = "English (Англійська)" },
        ["language_russian"] = { ru = "Русский", en = "Russian (Русский)", es = "Ruso (Русский)", pt = "Russo (Русский)", ko = "Russian (러시아어)", ja = "Russian (ロシア語)", uk = "Русский (Російська)" },
        ["language_spanish"] = { ru = "Español (Испанский)", en = "Spanish (Español)", es = "Español", pt = "Espanhol (Español)", ko = "Spanish (스페인어)", ja = "Spanish (スペイン語)", uk = "Español (Іспанська)" },
        ["language_portuguese"] = { ru = "Português (Португальский)", en = "Portuguese (Português)", es = "Portugués (Português)", pt = "Português", ko = "Portuguese (포르투갈어)", ja = "Portuguese (ポルトガル語)", uk = "Português (Португальська)" },
        ["language_korean"] = { ru = "한국어 (Корейский)", en = "Korean (한국어)", es = "Coreano (한국어)", pt = "Coreano (한국어)", ko = "한국어", ja = "Korean (韓国語)", uk = "한국어 (Корейська)" },
        ["language_japanese"] = { ru = "日本語 (Японский)", en = "Japanese (日本語)", es = "Japonés (日本語)", pt = "Japonês (日本語)", ko = "Japanese (일본어)", ja = "日本語", uk = "日本語 (Японська)" },
        ["language_ukrainian"] = { ru = "Украинский", en = "Ukrainian", es = "Ucraniano", pt = "Ucraniano", ko = "우크라이나어", ja = "ウクライナ語", uk = "Українська" },
        ["notify_language_changed"] = { ru = "🌍 Язык изменен на: %s", en = "🌍 Language changed to: %s", es = "🌍 Idioma cambiado a: %s", pt = "🌍 Idioma alterado para: %s", ko = "🌍 언어 변경됨: %s", ja = "🌍 言語変更: %s", uk = "🌍 Мову змінено на: %s" },
        ["slider_menu_transparency"] = { ru = "Прозрачность меню", en = "Menu Transparency", es = "Transparencia del menú", pt = "Transparência do Menu", ko = "메뉴 투명도", ja = "メニューの透明度", uk = "Прозорість меню" },
        ["keybind_menu"] = { ru = "🔑 Изменить клавишу меню", en = "🔑 Change Menu Key", es = "🔑 Cambiar Tecla del Menú", pt = "🔑 Alterar Tecla do Menu", ko = "🔑 메뉴 키 변경", ja = "🔑 メニューキー変更", uk = "🔑 Змінити клавішу меню" },
        ["toggle_show_notifications"] = { ru = "Показывать уведомления", en = "Show Notifications", es = "Mostrar Notificaciones", pt = "Mostrar Notificações", ko = "알림 표시", ja = "通知を表示", uk = "Показувати сповіщення" },
        ["section_settings_mobile_hud"] = { ru = "📱 МОБИЛЬНЫЕ КНОПКИ (HUD)", en = "📱 MOBILE HUD BUTTONS", es = "📱 BOTONES HUD MÓVIL", pt = "📱 BOTÕES HUD MOBILE", ko = "📱 모바일 HUD 버튼", ja = "📱 モバイルHUDボタン", uk = "📱 МОБІЛЬНІ КНОПКИ (HUD)" },
        ["toggle_menu_icon"] = { ru = "🔘 Показывать иконку меню", en = "🔘 Show Menu Icon", es = "🔘 Mostrar Icono de Menú", pt = "🔘 Mostrar Ícone de Menu", ko = "🔘 메뉴 아이콘 표시", ja = "🔘 メニューアイコンを表示", uk = "🔘 Показувати іконку меню" },
        ["toggle_killaura_mobile_btn"] = { ru = "📱 Показывать на экране (Quick Toggle)", en = "📱 Show on Screen (Quick Toggle)", es = "📱 Mostrar en pantalla", pt = "📱 Mostrar na Tela", ko = "📱 화면에 표시", ja = "📱 画面に表示", uk = "📱 Показувати на екрані" },
        ["toggle_aim_mobile_btn"] = { ru = "📱 Показывать на экране (Quick Toggle)", en = "📱 Show on Screen (Quick Toggle)", es = "📱 Mostrar en pantalla", pt = "📱 Mostrar na Tela", ko = "📱 화면에 표시", ja = "📱 画面に表示", uk = "📱 Показувати на екрані" },
        ["toggle_scaffold_mobile_btn"] = { ru = "📱 Показывать на экране (Quick Toggle)", en = "📱 Show on Screen (Quick Toggle)", es = "📱 Mostrar en pantalla", pt = "📱 Mostrar na Tela", ko = "📱 화면에 표시", ja = "📱 画面に表示", uk = "📱 Показувати на екрані" },
        ["button_cleanup"] = { ru = "🗑️ Очистить и выгрузить скрипт", en = "🗑️ Cleanup and Unload Script", es = "🗑️ Limpiar y Descargar Script", pt = "🗑️ Limpar e Descarregar Script", ko = "🗑️ 정리 및 스크립트 언로드", ja = "🗑️ クリーンアップとスクリプトアンロード", uk = "🗑️ Очистити та вивантажити скрипт" },
        ["section_player_list"] = { ru = "👥 СПИСОК ИГРОКОВ НА СЕРВЕРЕ", en = "👥 SERVER PLAYER LIST", es = "👥 LISTA DE JUGADORES DEL SERVIDOR", pt = "👥 LISTA DE JOGADORES DO SERVIDOR", ko = "👥 서버 플레이어 목록", ja = "👥 サーバープレイヤーリスト", uk = "👥 СПИСОК ГРАВЦІВ НА СЕРВЕРІ" },
        ["button_stop_spectate"] = { ru = "❌ Отключить наблюдение", en = "❌ Stop Spectating", es = "❌ Detener Espectador", pt = "❌ Parar de Espectar", ko = "❌ 관전 중지", ja = "❌ 観戦停止", uk = "❌ Вимкнути спостереження" },
        ["playerlist_name"] = { ru = "ИМЯ", en = "NAME", es = "NOMBRE", pt = "NOME", ko = "이름", ja = "名前", uk = "ІМ'Я" },
        ["playerlist_team"] = { ru = "КОМАНДА", en = "TEAM", es = "EQUIPO", pt = "TIME", ko = "팀", ja = "チーム", uk = "КОМАНДА" },
        ["playerlist_hp"] = { ru = "HP", en = "HP", es = "HP", pt = "HP", ko = "HP", ja = "HP", uk = "HP" },
        ["playerlist_dist"] = { ru = "ДИСТ.", en = "DIST.", es = "DIST.", pt = "DIST.", ko = "거리.", ja = "DIST.", uk = "ДИСТ." },
        ["playerlist_team_none"] = { ru = "НЕТ", en = "NONE", es = "NINGUNO", pt = "NENHUM", ko = "없음", ja = "なし", uk = "НЕМАЄ" },
        ["playerlist_hp_dead"] = { ru = "HP: DEAD", en = "HP: DEAD", es = "HP: MUERTO", pt = "HP: MORTO", ko = "HP: 죽음", ja = "HP: デッド", uk = "HP: МЕРТВИЙ" },
        ["playerlist_hp_format"] = { ru = "HP: %d", en = "HP: %d", es = "HP: %d", pt = "HP: %d", ko = "HP: %d", ja = "HP: %d", uk = "HP: %d" },
        ["playerlist_dist_none"] = { ru = "ДИСТ: ---", en = "DIST: ---", es = "DIST: ---", pt = "DIST: ---", ko = "거리: ---", ja = "DIST: ---", uk = "ДИСТ: ---" },
        ["playerlist_dist_format"] = { ru = "ДИСТ: %dм", en = "DIST: %dm", es = "DIST: %dm", pt = "DIST: %dm", ko = "거리: %dm", ja = "DIST: %dm", uk = "ДИСТ: %dм" },
        ["print_esp_on"] = { ru = "👁️ ESP: ВКЛЮЧЕН", en = "👁️ ESP: ENABLED", es = "👁️ ESP: HABILITADO", pt = "👁️ ESP: ATIVADO", ko = "👁️ ESP: 활성화됨", ja = "👁️ ESP: 有効", uk = "👁️ ESP: УВІМКНЕНО" },
        ["print_esp_off"] = { ru = "👁️ ESP: ВЫКЛЮЧЕН", en = "👁️ ESP: DISABLED", es = "👁️ ESP: DESHABILITADO", pt = "👁️ ESP: DESATIVADO", ko = "👁️ ESP: 비활성화됨", ja = "👁️ ESP: 無効", uk = "👁️ ESP: ВИМКНЕНО" },
        ["print_aim_on"] = { ru = "🎯 Aim Assist: ВКЛЮЧЕН", en = "🎯 Aim Assist: ENABLED", es = "🎯 Ayuda de Puntería: HABILITADA", pt = "🎯 Assistência de Mira: ATIVADA", ko = "🎯 조준 보조: 활성화됨", ja = "🎯 エイムアシスト: 有効", uk = "🎯 Aim Assist: УВІМКНЕНО" },
        ["print_aim_off"] = { ru = "🎯 Aim Assist: ВЫКЛЮЧЕН", en = "🎯 Aim Assist: DISABLED", es = "🎯 Ayuda de Puntería: DESHABILITADA", pt = "🎯 Assistência de Mira: DESATIVADA", ko = "🎯 조준 보조: 비활성화됨", ja = "🎯 エイムアシスト: 無効", uk = "🎯 Aim Assist: ВИМКНЕНО" },
        ["print_aim_active"] = { ru = "🎯 Aim Assist АКТИВИРОВАН", en = "🎯 Aim Assist ACTIVATED", es = "🎯 Ayuda de Puntería ACTIVADA", pt = "🎯 Assistência de Mira ATIVADA", ko = "🎯 조준 보조 활성화됨", ja = "🎯 エイムアシスト アクティブ", uk = "🎯 Aim Assist АКТИВОВАНО" },
        ["print_aim_inactive"] = { ru = "🎯 Aim Assist ДЕАКТИВИРОВАН", en = "🎯 Aim Assist DEACTIVATED", es = "🎯 Ayuda de Puntería DESACTIVADA", pt = "🎯 Assistência de Mira DESATIVADA", ko = "🎯 조준 보조 비활성화됨", ja = "🎯 エイムアシスト 非アクティブ", uk = "🎯 Aim Assist ДЕАКТИВОВАНО" },
        ["print_speed_on"] = { ru = "⚡ Speed Hack: %s единиц", en = "⚡ Speed Hack: %s units", es = "⚡ Hack de Velocidad: %s unidades", pt = "⚡ Hack de Velocidade: %s unidades", ko = "⚡ 속도 해킹: %s 유닛", ja = "⚡ スピードハック: %s ユニット", uk = "⚡ Speed Hack: %s одиниць" },
        ["print_speed_off"] = { ru = "⚡ Speed Hack: 16 единиц", en = "⚡ Speed Hack: 16 units", es = "⚡ Hack de Velocidad: 16 unidades", pt = "⚡ Hack de Velocidade: 16 unidades", ko = "⚡ 속도 해킹: 16 유닛", ja = "⚡ スピードハック: 16 ユニット", uk = "⚡ Speed Hack: 16 одиниць" },
        ["print_load_success"] = { ru = "🔥 TUMBA MEGA SYSTEM v%s УСПЕШНО ЗАГРУЖЕН!", en = "🔥 TUMBA MEGA SYSTEM v%s LOADED SUCCESSFULLY!", es = "🔥 SISTEMA MEGA TUMBA v%s CARGADO EXITOSAMENTE!", pt = "🔥 SISTEMA MEGA TUMBA v%s CARREGADO COM SUCESSO!", ko = "🔥 TUMBA 메가 시스템 v%s 성공적으로 로드됨!", ja = "🔥 TUMBA メガシステム v%s 正常に読み込まれました!", uk = "🔥 TUMBA MEGA SYSTEM v%s УСПІШНО ЗАВАНТАЖЕНО!" },
        ["print_created_by"] = { ru = "💎 Создано: %s", en = "💎 Created by: %s", es = "💎 Creado por: %s", pt = "💎 Criado por: %s", ko = "💎 제작: %s", ja = "💎 作成: %s", uk = "💎 Створено: %s" },
        ["print_for"] = { ru = "🎯 Специально для: %s", en = "🎯 Especially for: %s", es = "🎯 Especialmente para: %s", pt = "🎯 Especialmente para: %s", ko = "🎯 특별히 위해: %s", ja = "🎯 特にために: %s", uk = "🎯 Спеціально для: %s" },
        ["print_build_date"] = { ru = "📅 Сборка: %s", en = "📅 Build: %s", es = "📅 Compilación: %s", pt = "📅 Compilação: %s", ko = "📅 빌드: %s", ja = "📅 ビルド: %s", uk = "📅 Збірка: %s" },
        ["print_menu_key"] = { ru = "🎮 Используйте %s для открытия меню", en = "🎮 Use %s to open the menu", es = "🎮 Usa %s para abrir el menú", pt = "🎮 Use %s para abrir o menu", ko = "🎮 메뉴 열기에 %s 사용", ja = "🎮 メニューを開くために %s を使用", uk = "🎮 Використовуйте %s для відкриття меню" },
        ["print_esp_ready"] = { ru = "👁️ ESP готов к использованию", en = "👁️ ESP is ready to use", es = "👁️ ESP listo para usar", pt = "👁️ ESP pronto para usar", ko = "👁️ ESP 사용 준비됨", ja = "👁️ ESP 使用準備完了", uk = "👁️ ESP готовий до використання" },
        ["print_kit_esp_ready"] = { ru = "🛠️ Kit ESP добавлен и готов к использованию", en = "🛠️ Kit ESP added and ready to use", es = "🛠️ Kit ESP agregado y listo para usar", pt = "🛠️ Kit ESP adicionado e pronto para usar", ko = "🛠️ Kit ESP 추가 및 사용 준비됨", ja = "🛠️ Kit ESP 追加され使用準備完了", uk = "🛠️ Kit ESP додано і готовий до використання" },
        ["print_aim_ready"] = { ru = "🎯 Aim Assist готов (Нажми %s для активации)", en = "🎯 Aim Assist ready (Press %s to activate)", es = "🎯 Ayuda de Puntería lista (Presiona %s para activar)", pt = "🎯 Assistência de Mira pronta (Pressione %s para ativar)", ko = "🎯 조준 보조 준비됨 (%s 누르기 활성화)", ja = "🎯 エイムアシスト 準備完了 (%s を押してアクティブ)", uk = "🎯 Aim Assist готовий (Натисни %s для активації)" },
        ["print_all_ready"] = { ru = "⚡ Все функции активированы!", en = "⚡ All functions activated!", es = "⚡ ¡Todas las funciones activadas!", pt = "⚡ Todas as funções ativadas!", ko = "⚡ 모든 기능 활성화됨!", ja = "⚡ すべての機能がアクティブ!", uk = "⚡ Всі функції активовані!" },
        ["print_menu_open"] = { ru = "🚀 TUMBA MEGA SYSTEM v%s АКТИВИРОВАН", en = "🚀 TUMBA MEGA SYSTEM v%s ACTIVATED", es = "🚀 SISTEMA MEGA TUMBA v%s ACTIVADO", pt = "🚀 SISTEMA MEGA TUMBA v%s ATIVADO", ko = "🚀 TUMBA 메가 시스템 v%s 활성화됨", ja = "🚀 TUMBA メガシステム v%s アクティブ", uk = "🚀 TUMBA MEGA SYSTEM v%s АКТИВОВАНО" },
        ["print_menu_navigate"] = { ru = "📁 Используйте вкладки для навигации", en = "📁 Use tabs to navigate", es = "📁 Usa pestañas para navegar", pt = "📁 Use abas para navegar", ko = "📁 탭으로 탐색", ja = "📁 タブでナビゲート", uk = "📁 Використовуйте вкладки для навігації" },
        ["print_menu_closed"] = { ru = "📱 Меню закрыто", en = "📱 Menu closed", es = "📱 Menú cerrado", pt = "📱 Menu fechado", ko = "📱 메뉴 닫힘", ja = "📱 メニュー閉じ", uk = "📱 Меню закрито" },
        ["esp_studs"] = { ru = "%d studs", en = "%d studs", es = "%d studs", pt = "%d studs", ko = "%d 스터드", ja = "%d スタッド", uk = "%d стадів" },
        ["esp_hp"] = { ru = "HP: %d", en = "HP: %d", es = "HP: %d", pt = "HP: %d", ko = "HP: %d", ja = "HP: %d", uk = "HP: %d" },
    }
}

--- Returns the localized text for a given key.
---@param key string
---@vararg any
---@return string
function Mega.GetText(key, ...)
    local lang = Mega.Localization.CurrentLanguage
    local str = Mega.Localization.Strings[key]

    if str and str[lang] then
        local text = str[lang]
        local args = {...}
        if #args > 0 then
            -- Use pcall for safety in case of formatting errors
            local success, result = pcall(string.format, text, ...)
            if success then
                return result
            else
                return text -- Return raw text on format error
            end
        else
            return text
        end
    else
        return key -- Return key if no translation is found
    end
end

function Mega.SaveLanguage(lang)
    if writefile then
        if not isfolder("tumbaHub") then pcall(makefolder, "tumbaHub") end
        if not isfolder("tumbaHub/configs") then pcall(makefolder, "tumbaHub/configs") end
        pcall(writefile, "tumbaHub/configs/Language.txt", lang)
    end
end

function Mega.LoadLanguage()
    if readfile and isfile then
        if isfile("tumbaHub/configs/Language.txt") then
            local success, lang = pcall(readfile, "tumbaHub/configs/Language.txt")
            if success and lang then return lang end
        elseif isfile("TumbaLanguage.txt") then
            local success, lang = pcall(readfile, "TumbaLanguage.txt")
            if success and lang then 
                Mega.SaveLanguage(lang) -- Переносим в новую папку
                return lang 
            end
        end
    end
    return "en" -- Default to English if loading fails
end

-- Load saved language on startup
Mega.Localization.CurrentLanguage = Mega.LoadLanguage()

function Mega.HasSavedLanguage()
    return (isfile and (isfile("tumbaHub/configs/Language.txt") or isfile("TumbaLanguage.txt")))
end
